codecov:
  branch: dev

coverage:
  range: 70..100
  round: down
  precision: 5
  status:
    project:
      default:
        threshold: 2%
    patch:
      default:
        threshold: 1%

  ignore:
    - "docs/*"
    - "experiments/*"
    - "misc/*"
    - "test/*"

comment:
  layout: "header, diff, changes, sunburst, uncovered"
  behavior: default
